"Табы и пробелы
set expandtab
set smarttab
set tabstop=4
set softtabstop=4
set shiftwidth=4

"Нумерация строк и отступ
set number
set foldcolumn=2

"Цветовая схема
colorscheme dark
syntax on

"Без звука
set noerrorbells
set novisualbell

"Мышь
set mouse=a

"Привязки
let mapleader = ","
nmap <leader>w :w!<CR>
map <space> /
map <C-space> ?
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
map <leader>ss :setlocal spell!<CR>
inoremap <C-v> <ESC>"+pa
vnoremap <C-c> "+y
vnoremap <C-d> "+d

"Поиск
set ignorecase
set smartcase 
set hlsearch
set incsearch

"Выход с sudo 
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
 
"Кодировка
set encoding=utf8
 
"Тип переноса
set ffs=unix,dos,mac                                                                                                                                            
